name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: stefanoeb/eslint-action@1.0.2
      with:
        files: src/
    # - name: Run ESLint
    #   run: make lint
